name: Kadin Hernandez Country
favicon: null
layout_spectrum: 0.29533
typography_spectrum: 0.6345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#d4946e'
    - '#4b4336'
    - '#f3c7bc'
    - '#aae3f7'
  brandStrength: 0.1875
  lightness: 0.530537742190063
  saturation: 0.3125
  rhythmicContrast: 0.9893675830680877
purpose: []
