name: Kadin Hernandez Country
favicon: null
layout_spectrum: 0.5145667949691415
typography_spectrum: 0.5821835224051028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10990917845629156
  lightness: 0.530537742190063
  saturation: 0.45717634656466544
  rhythmicContrast: 0.9893675830680877
purpose: []
