name: Kadin Hernandez Country
favicon: null
layout_spectrum: 0.29533
typography_spectrum: 0.71205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#954c00'
    - '#808080'
    - '#d0b487'
  brandStrength: 0.3125
  lightness: 0.530537742190063
  saturation: 0.3125
  rhythmicContrast: 0.9893675830680877
purpose: []
